// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/athletes" | "/athletes/[id]" | "/athletes/[id]/edit" | "/athletes/new" | "/attendance" | "/calendar" | "/calendar/[id]" | "/calendar/[id]/edit" | "/calendar/new" | "/check-in" | "/competitions" | "/competitions/[id]" | "/dashboard" | "/documents" | "/finances" | "/inventory" | "/onboarding" | "/payments" | "/payments/new" | "/plans" | "/plans/[id]" | "/plans/[id]/edit" | "/plans/new" | "/rules" | "/settings" | "/sign-in/[[...sign-in]]" | "/sign-up/[[...sign-up]]" | "/subscriptions" | "/subscriptions/new" | "/venues"
type AppRouteHandlerRoutes = "/api/attendance/check-in" | "/api/attendance/token" | "/api/webhooks/clerk"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/attendance/check-in": {}
  "/api/attendance/token": {}
  "/api/webhooks/clerk": {}
  "/athletes": {}
  "/athletes/[id]": { "id": string; }
  "/athletes/[id]/edit": { "id": string; }
  "/athletes/new": {}
  "/attendance": {}
  "/calendar": {}
  "/calendar/[id]": { "id": string; }
  "/calendar/[id]/edit": { "id": string; }
  "/calendar/new": {}
  "/check-in": {}
  "/competitions": {}
  "/competitions/[id]": { "id": string; }
  "/dashboard": {}
  "/documents": {}
  "/finances": {}
  "/inventory": {}
  "/onboarding": {}
  "/payments": {}
  "/payments/new": {}
  "/plans": {}
  "/plans/[id]": { "id": string; }
  "/plans/[id]/edit": { "id": string; }
  "/plans/new": {}
  "/rules": {}
  "/settings": {}
  "/sign-in/[[...sign-in]]": { "sign-in"?: string[]; }
  "/sign-up/[[...sign-up]]": { "sign-up"?: string[]; }
  "/subscriptions": {}
  "/subscriptions/new": {}
  "/venues": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
